package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.AccountSubject;
import cn.ahyc.yjz.model.AccountSubjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AccountSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int countByExample(AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int deleteByExample(AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int insert(AccountSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int insertSelective(AccountSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    List<AccountSubject> selectByExample(AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    AccountSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccountSubject record, @Param("example") AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int updateByExample(@Param("record") AccountSubject record, @Param("example") AccountSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int updateByPrimaryKeySelective(AccountSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_subject
     *
     * @mbggenerated Wed Sep 23 16:59:46 CST 2015
     */
    int updateByPrimaryKey(AccountSubject record);

    /**
     * 根据大分类获取所有会计科目.
     *
     * @param param
     * @return
     */
    List<Map<String, Object>> getSubjectsByCategoryId(Map<String, Object> param);

    /**
     * 根据父级id获取所有子级.
     *
     * @param param
     * @return
     */
    List<Map<String, Object>> getChildrenSubjectsByCategoryId(Map<String, Object> param);
}