package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.CashFlow;
import cn.ahyc.yjz.model.CashFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CashFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int countByExample(CashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int deleteByExample(CashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int insert(CashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int insertSelective(CashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    List<CashFlow> selectByExample(CashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    CashFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") CashFlow record, @Param("example") CashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByExample(@Param("record") CashFlow record, @Param("example") CashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByPrimaryKeySelective(CashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByPrimaryKey(CashFlow record);
}