package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.CashFlowData;
import cn.ahyc.yjz.model.CashFlowDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CashFlowDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int countByExample(CashFlowDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int deleteByExample(CashFlowDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int insert(CashFlowData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int insertSelective(CashFlowData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    List<CashFlowData> selectByExample(CashFlowDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    CashFlowData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") CashFlowData record, @Param("example") CashFlowDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByExample(@Param("record") CashFlowData record, @Param("example") CashFlowDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByPrimaryKeySelective(CashFlowData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Wed Oct 28 17:00:31 CST 2015
     */
    int updateByPrimaryKey(CashFlowData record);
}