package cn.ahyc.yjz.mapper.base;

import cn.ahyc.yjz.model.Profit;
import cn.ahyc.yjz.model.ProfitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int countByExample(ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int deleteByExample(ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int insert(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int insertSelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    List<Profit> selectByExample(ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    Profit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") Profit record, @Param("example") ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByExample(@Param("record") Profit record, @Param("example") ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByPrimaryKeySelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    int updateByPrimaryKey(Profit record);
}