package cn.ahyc.yjz.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CashFlow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.id
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.cash_code
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private String cashCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.static_code
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private String staticCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.name
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.calcu_type
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private Integer calcuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.from_flag
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private Integer fromFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.money
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.create_time
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow.modify_time
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public CashFlow(Long id, String cashCode, String staticCode, String name, Integer calcuType, Integer fromFlag, BigDecimal money, Date createTime, Date modifyTime) {
        this.id = id;
        this.cashCode = cashCode;
        this.staticCode = staticCode;
        this.name = name;
        this.calcuType = calcuType;
        this.fromFlag = fromFlag;
        this.money = money;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public CashFlow() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.id
     *
     * @return the value of cash_flow.id
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.id
     *
     * @param id the value for cash_flow.id
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.cash_code
     *
     * @return the value of cash_flow.cash_code
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public String getCashCode() {
        return cashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.cash_code
     *
     * @param cashCode the value for cash_flow.cash_code
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setCashCode(String cashCode) {
        this.cashCode = cashCode == null ? null : cashCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.static_code
     *
     * @return the value of cash_flow.static_code
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public String getStaticCode() {
        return staticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.static_code
     *
     * @param staticCode the value for cash_flow.static_code
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setStaticCode(String staticCode) {
        this.staticCode = staticCode == null ? null : staticCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.name
     *
     * @return the value of cash_flow.name
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.name
     *
     * @param name the value for cash_flow.name
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.calcu_type
     *
     * @return the value of cash_flow.calcu_type
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Integer getCalcuType() {
        return calcuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.calcu_type
     *
     * @param calcuType the value for cash_flow.calcu_type
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setCalcuType(Integer calcuType) {
        this.calcuType = calcuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.from_flag
     *
     * @return the value of cash_flow.from_flag
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Integer getFromFlag() {
        return fromFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.from_flag
     *
     * @param fromFlag the value for cash_flow.from_flag
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setFromFlag(Integer fromFlag) {
        this.fromFlag = fromFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.money
     *
     * @return the value of cash_flow.money
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.money
     *
     * @param money the value for cash_flow.money
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.create_time
     *
     * @return the value of cash_flow.create_time
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.create_time
     *
     * @param createTime the value for cash_flow.create_time
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow.modify_time
     *
     * @return the value of cash_flow.modify_time
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow.modify_time
     *
     * @param modifyTime the value for cash_flow.modify_time
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}