package cn.ahyc.yjz.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CashFlowData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.cash_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private String cashCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.subject_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Long subjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.relative_subject_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Long relativeSubjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.money
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.book_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.period_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Long periodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.create_time
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.modify_time
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_flow_data.voucher_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private Long voucherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cash_flow_data
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public CashFlowData(Long id, String cashCode, Long subjectCode, Long relativeSubjectCode, BigDecimal money, Long bookId, Long periodId, Date createTime, Date modifyTime, Long voucherId) {
        this.id = id;
        this.cashCode = cashCode;
        this.subjectCode = subjectCode;
        this.relativeSubjectCode = relativeSubjectCode;
        this.money = money;
        this.bookId = bookId;
        this.periodId = periodId;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.voucherId = voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow_data
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public CashFlowData() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.id
     *
     * @return the value of cash_flow_data.id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.id
     *
     * @param id the value for cash_flow_data.id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.cash_code
     *
     * @return the value of cash_flow_data.cash_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public String getCashCode() {
        return cashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.cash_code
     *
     * @param cashCode the value for cash_flow_data.cash_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setCashCode(String cashCode) {
        this.cashCode = cashCode == null ? null : cashCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.subject_code
     *
     * @return the value of cash_flow_data.subject_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Long getSubjectCode() {
        return subjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.subject_code
     *
     * @param subjectCode the value for cash_flow_data.subject_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setSubjectCode(Long subjectCode) {
        this.subjectCode = subjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.relative_subject_code
     *
     * @return the value of cash_flow_data.relative_subject_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Long getRelativeSubjectCode() {
        return relativeSubjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.relative_subject_code
     *
     * @param relativeSubjectCode the value for cash_flow_data.relative_subject_code
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setRelativeSubjectCode(Long relativeSubjectCode) {
        this.relativeSubjectCode = relativeSubjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.money
     *
     * @return the value of cash_flow_data.money
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.money
     *
     * @param money the value for cash_flow_data.money
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.book_id
     *
     * @return the value of cash_flow_data.book_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.book_id
     *
     * @param bookId the value for cash_flow_data.book_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.period_id
     *
     * @return the value of cash_flow_data.period_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Long getPeriodId() {
        return periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.period_id
     *
     * @param periodId the value for cash_flow_data.period_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setPeriodId(Long periodId) {
        this.periodId = periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.create_time
     *
     * @return the value of cash_flow_data.create_time
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.create_time
     *
     * @param createTime the value for cash_flow_data.create_time
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.modify_time
     *
     * @return the value of cash_flow_data.modify_time
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.modify_time
     *
     * @param modifyTime the value for cash_flow_data.modify_time
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_flow_data.voucher_id
     *
     * @return the value of cash_flow_data.voucher_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public Long getVoucherId() {
        return voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_flow_data.voucher_id
     *
     * @param voucherId the value for cash_flow_data.voucher_id
     *
     * @mbggenerated Thu Oct 29 14:04:01 CST 2015
     */
    public void setVoucherId(Long voucherId) {
        this.voucherId = voucherId;
    }
}