package cn.ahyc.yjz.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CashFlowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public CashFlowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCashCodeIsNull() {
            addCriterion("cash_code is null");
            return (Criteria) this;
        }

        public Criteria andCashCodeIsNotNull() {
            addCriterion("cash_code is not null");
            return (Criteria) this;
        }

        public Criteria andCashCodeEqualTo(String value) {
            addCriterion("cash_code =", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeNotEqualTo(String value) {
            addCriterion("cash_code <>", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeGreaterThan(String value) {
            addCriterion("cash_code >", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cash_code >=", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeLessThan(String value) {
            addCriterion("cash_code <", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeLessThanOrEqualTo(String value) {
            addCriterion("cash_code <=", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeLike(String value) {
            addCriterion("cash_code like", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeNotLike(String value) {
            addCriterion("cash_code not like", value, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeIn(List<String> values) {
            addCriterion("cash_code in", values, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeNotIn(List<String> values) {
            addCriterion("cash_code not in", values, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeBetween(String value1, String value2) {
            addCriterion("cash_code between", value1, value2, "cashCode");
            return (Criteria) this;
        }

        public Criteria andCashCodeNotBetween(String value1, String value2) {
            addCriterion("cash_code not between", value1, value2, "cashCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeIsNull() {
            addCriterion("static_code is null");
            return (Criteria) this;
        }

        public Criteria andStaticCodeIsNotNull() {
            addCriterion("static_code is not null");
            return (Criteria) this;
        }

        public Criteria andStaticCodeEqualTo(String value) {
            addCriterion("static_code =", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeNotEqualTo(String value) {
            addCriterion("static_code <>", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeGreaterThan(String value) {
            addCriterion("static_code >", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeGreaterThanOrEqualTo(String value) {
            addCriterion("static_code >=", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeLessThan(String value) {
            addCriterion("static_code <", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeLessThanOrEqualTo(String value) {
            addCriterion("static_code <=", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeLike(String value) {
            addCriterion("static_code like", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeNotLike(String value) {
            addCriterion("static_code not like", value, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeIn(List<String> values) {
            addCriterion("static_code in", values, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeNotIn(List<String> values) {
            addCriterion("static_code not in", values, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeBetween(String value1, String value2) {
            addCriterion("static_code between", value1, value2, "staticCode");
            return (Criteria) this;
        }

        public Criteria andStaticCodeNotBetween(String value1, String value2) {
            addCriterion("static_code not between", value1, value2, "staticCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeIsNull() {
            addCriterion("calcu_type is null");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeIsNotNull() {
            addCriterion("calcu_type is not null");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeEqualTo(Integer value) {
            addCriterion("calcu_type =", value, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeNotEqualTo(Integer value) {
            addCriterion("calcu_type <>", value, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeGreaterThan(Integer value) {
            addCriterion("calcu_type >", value, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("calcu_type >=", value, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeLessThan(Integer value) {
            addCriterion("calcu_type <", value, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeLessThanOrEqualTo(Integer value) {
            addCriterion("calcu_type <=", value, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeIn(List<Integer> values) {
            addCriterion("calcu_type in", values, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeNotIn(List<Integer> values) {
            addCriterion("calcu_type not in", values, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeBetween(Integer value1, Integer value2) {
            addCriterion("calcu_type between", value1, value2, "calcuType");
            return (Criteria) this;
        }

        public Criteria andCalcuTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("calcu_type not between", value1, value2, "calcuType");
            return (Criteria) this;
        }

        public Criteria andFromFlagIsNull() {
            addCriterion("from_flag is null");
            return (Criteria) this;
        }

        public Criteria andFromFlagIsNotNull() {
            addCriterion("from_flag is not null");
            return (Criteria) this;
        }

        public Criteria andFromFlagEqualTo(Integer value) {
            addCriterion("from_flag =", value, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagNotEqualTo(Integer value) {
            addCriterion("from_flag <>", value, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagGreaterThan(Integer value) {
            addCriterion("from_flag >", value, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("from_flag >=", value, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagLessThan(Integer value) {
            addCriterion("from_flag <", value, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagLessThanOrEqualTo(Integer value) {
            addCriterion("from_flag <=", value, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagIn(List<Integer> values) {
            addCriterion("from_flag in", values, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagNotIn(List<Integer> values) {
            addCriterion("from_flag not in", values, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagBetween(Integer value1, Integer value2) {
            addCriterion("from_flag between", value1, value2, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andFromFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("from_flag not between", value1, value2, "fromFlag");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cash_flow
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 03 15:43:41 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cash_flow
     *
     * @mbggenerated Tue Nov 03 15:43:41 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}