package cn.ahyc.yjz.model;

import java.io.Serializable;
import java.util.Date;

public class Profit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.id
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.name
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.row_num
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private Integer rowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.year_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private String yearExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.month_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private String monthExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.last_year_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private String lastYearExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.create_time
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.modify_time
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public Profit(Long id, String name, Integer rowNum, String yearExp, String monthExp, String lastYearExp, Date createTime, Date modifyTime) {
        this.id = id;
        this.name = name;
        this.rowNum = rowNum;
        this.yearExp = yearExp;
        this.monthExp = monthExp;
        this.lastYearExp = lastYearExp;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public Profit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.id
     *
     * @return the value of profit.id
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.id
     *
     * @param id the value for profit.id
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.name
     *
     * @return the value of profit.name
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.name
     *
     * @param name the value for profit.name
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.row_num
     *
     * @return the value of profit.row_num
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public Integer getRowNum() {
        return rowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.row_num
     *
     * @param rowNum the value for profit.row_num
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setRowNum(Integer rowNum) {
        this.rowNum = rowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.year_exp
     *
     * @return the value of profit.year_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public String getYearExp() {
        return yearExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.year_exp
     *
     * @param yearExp the value for profit.year_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setYearExp(String yearExp) {
        this.yearExp = yearExp == null ? null : yearExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.month_exp
     *
     * @return the value of profit.month_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public String getMonthExp() {
        return monthExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.month_exp
     *
     * @param monthExp the value for profit.month_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setMonthExp(String monthExp) {
        this.monthExp = monthExp == null ? null : monthExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.last_year_exp
     *
     * @return the value of profit.last_year_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public String getLastYearExp() {
        return lastYearExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.last_year_exp
     *
     * @param lastYearExp the value for profit.last_year_exp
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setLastYearExp(String lastYearExp) {
        this.lastYearExp = lastYearExp == null ? null : lastYearExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.create_time
     *
     * @return the value of profit.create_time
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.create_time
     *
     * @param createTime the value for profit.create_time
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.modify_time
     *
     * @return the value of profit.modify_time
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.modify_time
     *
     * @param modifyTime the value for profit.modify_time
     *
     * @mbggenerated Tue Oct 27 09:48:11 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}